### PR TITLE
Fix #388: Normalize IL to ensure consistent outcome.

### LINKED ISSUE #388: Normalize IL to ensure consistent outcome.
#### Is the feature request related to a problem

Tests occasionally break just because the layout has changed (class/member ordering), while the IL itself is still the same. 
see e.g. https://ci.appveyor.com/project/tom-englert/nullguard

see also https://github.com/icsharpcode/ILSpy/issues/2834

#### Describe the solution

Add option to sort IL output:
https://github.com/icsharpcode/ILSpy/pull/2835

either
- wait until new version of the de-compiler is available
- temporarily copy the source code changes of https://github.com/icsharpcode/ILSpy/pull/2835, so we can have an early release

#### Additional context

Should sorted output be the default (breaking change!) with the possibility to opt out, or better opt in (but you need to do it every time)

### PR DESCRIPTION
**Pull request by tom-englert**

### CODE REVIEW

**Comment by tom-englert** [comment]
@SimonCropp any idea why that damn RVA is different when building on AppVeyor?

**Comment by SimonCropp** [comment]
no idea

**Comment by tom-englert** [comment]
Possible solutions
1. omit that test
2. always remove RVA, no backward compatiblity
3. separate setting to control RVA behavior

@SimonCropp would you go for?

**Comment by SimonCropp** [comment]
lets go with remove rva

**Comment by tom-englert** [comment]
OK, ready for review

**Pull request merged**
